menu:
- {name: 'News', url: '/news'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/teaching'}
- {name: 'Courses', url: '/courses'}
#- {name: 'My Research Group', url: '/myResearchGroup'}
#- {name: 'My Reading Group', url: '/https://theo-physics.github.io/'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}


courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}
- {name: 'IELTS', url: 'ielts'}
- {name: 'Self-teach Physics', url: 'self-teach_physics'}


social:
- {icon: 'fab fa-github fa-3x', link: 'https://github.com/sarapv'}
- {icon: 'fab fa-linkedin fa-3x', link: 'https://www.linkedin.com/in/sara-p%C3%A9rez-vieites-732425122/'}
- {icon: 'ai ai-google-scholar fa-3x', link: 'https://scholar.google.es/citations?user=MzPUI0AAAAAJ&hl=en'}
- {icon: 'fab fa-orcid fa-3x', link: 'https://orcid.org/0000-0003-1572-4258'}
- {icon: 'ai ai-clarivate fa-3x', link: 'https://www.webofscience.com/wos/author/record/GOH-0455-2022'}
